[tox]
requires =
    tox>=4
    tox-uv>=1.0.0
isolated_build = True
envlist =
    py314
    test
    types
    lint
    docs
    security
skip_missing_interpreters = True
default_base_python = 314

[testenv:test]
description = Run tests with coverage
dependency_groups = tests
commands =
    pytest tests

[testenv:types]
description = Run static type checks
ignore_errors = true
dependency_groups =
    typing
    tests
commands =
    mypy --install-types \
        -p=ether \
        --non-interactive
    mypy --install-types tests \
        --non-interactive
    ty check ether tests

[testenv:docs]
description = Test documentation build
dependency_groups = docs
commands =
    zensical build

[testenv:security]
description = Run Security checks
ignore_outcome = true
dependency_groups = security
commands =
    bandit -q -r ether
    uv audit --preview-features audit

[testenv:lint]
description = Run linters
dependency_groups = lint
ignore_errors = true
commands =
    ruff check
    ruff format --check
    ssort --check
    zizmor .github
    just --check --fmt
